spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_techstore?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: MYSQL
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
